steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-west1-docker.pkg.dev/cs144-25s-team16/doodly-gae-repo/doodly:v1",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west1-docker.pkg.dev/cs144-25s-team16/doodly-gae-repo/doodly:v1",
      ]

  - name: "gcr.io/cloud-builders/kubectl"
    env:
      - "CLOUDSDK_COMPUTE_REGION=us-west1"
      - "CLOUDSDK_CONTAINER_CLUSTER=doodly-cluster"
    args: ["apply", "-f", "k8s/"]

images:
  - "us-west1-docker.pkg.dev/cs144-25s-team16/doodly-gae-repo/doodly:v1"
